# Generated by Django 4.2.11 on 2024-03-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/conducteurs/'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/vehicules/'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
