# Generated by Django 4.2.11 on 2024-03-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_auto', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('depenses_supplementaire', 'Depenses Supplementaire'), ('depannage', 'Depannage')], max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_auto.vehicule')),
            ],
        ),
    ]
