# Generated by Django 4.2.11 on 2024-03-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_auto', '0004_frais'),
    ]

    operations = [
        migrations.AddField(
            model_name='frais',
            name='Facture',
            field=models.ImageField(blank=True, null=True, upload_to='photos/Factures/'),
        ),
    ]
