# Generated by Django 4.2.11 on 2024-03-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_auto', '0005_frais_facture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frais',
            options={'verbose_name_plural': 'Frais'},
        ),
    ]
